### ISSUE TITLE
Speed_paramters of my own trained models

### ISSUE THREAD

**Issue by bis70** [ltkong218/IFRNet#20]
Hello,

how can I test the speed_paramters of my own trained models. i cant use the pth s

Thank You

**Comment by ltkong218** [comment]
The running speed and number of parameters do not rely on the trained parameter or state dict. You can load your trained models by <code>model.load_state_dict(torch.load('checkpoints/path/your_model.pth'))</code>.

**Comment by bis70** [comment]
that's right, no idea what I was thinking, thank you
